<a href="https://colab.research.google.com/github/SHAGGY670/SFC-foundations/blob/master/Data_Preprocessing_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

## Importing the libraries

In [135]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing Dataset

In [136]:
ds=pd.read_csv('Covid_Data.csv')
x=ds.iloc[:,:-1].values
y=ds.iloc[:,-1].values

In [137]:
print(x)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [138]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']





## Handling Missing Data

cannot use in string columns


In [139]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 0:1])
x[: , 0:1] = imputer.transform(x[:, 0:1])

In [140]:
print(x)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]

In [141]:
imputer.fit(x[:,4:5])
x[:,4:5]=imputer.transform(x[:,4:5])

In [142]:
print(x)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

## Encoding Categorical Data

In [143]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [144]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
x = np.array(ct.fit_transform(x))



In [145]:
print(x)

[[0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 12.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 15.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 12.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 15.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 18.0 'no' 'no' 66.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 17.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 16.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 25.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 24.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 30.0 'no' 'no' 62.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 89.0]
 [0.0 0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 0.0 1.0 26.0 'no' 'no' 82.07246376811594]
 [0.0 0.0 1.0 28.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 30.0 'yes' 'no' 86.0]
 [0.0 1.0 0.0 35.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 32.0 'no' 'yes' 84.0]
 [0.

### Encoding independent variables

### Encoding dependent variables

In [146]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
x[:,5]=le.fit_transform(x[:,5])
x[:,4]=le.fit_transform(x[:,4])


In [147]:
print(y)
print(x)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]
[[0.0 0.0 1.0 10.0 0 0 97.0]
 [0.0 0.0 1.0 12.0 0 0 97.0]
 [0.0 0.0 1.0 15.0 0 0 94.0]
 [0.0 0.0 1.0 10.0 0 0 97.0]
 [0.0 1.0 0.0 13.0 0 0 94.0]
 [0.0 1.0 0.0 12.0 0 0 97.0]
 [0.0 1.0 0.0 13.0 0 0 93.0]
 [0.0 1.0 0.0 15.0 0 0 92.0]
 [0.0 1.0 0.0 18.0 0 0 66.0]
 [0.0 0.0 1.0 19.0 0 0 92.0]
 [0.0 0.0 1.0 20.0 0 0 93.0]
 [0.0 0.0 1.0 17.0 0 0 93.0]
 [0.0 0.0 1.0 16.0 0 0 92.0]
 [0.0 0.0 1.0 18.0 0 0 93.0]
 [0.0 0.0 1.0 20.0 0 0 92.0]
 [0.0 1.0 0.0 25.0 0 0 93.0]
 [0.0 1.0 0.0 24.0 0 0 92.0]
 [1.0 0.0 0.0 26.0 0 0 94.0]
 [0.0 0.0 1.0 28.0 0 0 99.0]
 [0.0 0.0 1.0 29.0 0 0 93.0]
 [0.0 1.0 0.0 30.0 0 0 62.0]
 [0.0 0.0 1.0 19.0 0 0 89.0]
 [0.0 0.0 1.0 25.0 0 1 86.0]
 [0.0 0.0 1.0 26.0 0 0 82.07246376811594]
 [0.0 0.0 1.0 28.0 0 0 89.0]
 [0.0 1.0 0.0 30.0 1 0 86.0]
 [0.0 1.0 0.0 35.0 0 0 89.0]
 [0.0 1.0 0.0 32.0 0 1 84.0]
 [0.0 1.0 0.0 45.130434782608695

In [148]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [149]:
print(xtrain)

[[1.0 0.0 0.0 86.0 1 1 71.0]
 [0.0 1.0 0.0 35.0 0 1 92.0]
 [1.0 0.0 0.0 75.0 0 1 72.0]
 [1.0 0.0 0.0 42.0 0 0 92.0]
 [1.0 0.0 0.0 74.0 1 1 75.0]
 [1.0 0.0 0.0 62.0 1 1 68.0]
 [0.0 1.0 0.0 24.0 0 0 92.0]
 [0.0 1.0 0.0 48.0 0 1 93.0]
 [1.0 0.0 0.0 58.0 0 0 70.0]
 [0.0 1.0 0.0 45.130434782608695 1 0 90.0]
 [0.0 1.0 0.0 15.0 0 0 92.0]
 [0.0 0.0 1.0 70.0 0 1 88.0]
 [1.0 0.0 0.0 52.0 1 1 80.0]
 [1.0 0.0 0.0 60.0 1 1 68.0]
 [1.0 0.0 0.0 54.0 1 1 70.0]
 [0.0 0.0 1.0 29.0 0 0 93.0]
 [1.0 0.0 0.0 78.0 1 1 71.0]
 [1.0 0.0 0.0 36.0 1 0 90.0]
 [0.0 1.0 0.0 30.0 1 0 86.0]
 [1.0 0.0 0.0 50.0 1 1 77.0]
 [0.0 0.0 1.0 18.0 0 0 93.0]
 [1.0 0.0 0.0 69.0 0 1 53.0]
 [0.0 0.0 1.0 10.0 0 0 97.0]
 [1.0 0.0 0.0 26.0 0 0 94.0]
 [0.0 1.0 0.0 18.0 0 0 66.0]
 [1.0 0.0 0.0 62.0 1 1 69.0]
 [0.0 1.0 0.0 13.0 0 0 93.0]
 [1.0 0.0 0.0 40.0 0 0 92.0]
 [1.0 0.0 0.0 84.0 1 1 75.0]
 [1.0 0.0 0.0 76.0 1 1 80.0]
 [1.0 0.0 0.0 81.0 1 1 75.0]
 [0.0 1.0 0.0 25.0 0 0 93.0]
 [0.0 1.0 0.0 32.0 0 1 84.0]
 [1.0 0.0 0.0 56.0 1 1 77.0]


In [150]:
print(xtest)

[[0.0 0.0 1.0 25.0 0 1 86.0]
 [0.0 0.0 1.0 10.0 0 0 97.0]
 [1.0 0.0 0.0 68.0 1 0 67.0]
 [0.0 1.0 0.0 13.0 0 0 94.0]
 [1.0 0.0 0.0 59.0 1 0 68.0]
 [0.0 0.0 1.0 28.0 0 0 99.0]
 [0.0 0.0 1.0 20.0 0 0 93.0]
 [1.0 0.0 0.0 46.0 1 0 91.0]
 [1.0 0.0 0.0 53.0 1 0 55.0]
 [0.0 0.0 1.0 16.0 0 0 92.0]
 [1.0 0.0 0.0 38.0 0 0 75.0]
 [0.0 0.0 1.0 19.0 0 0 92.0]
 [1.0 0.0 0.0 94.0 1 1 64.0]
 [0.0 1.0 0.0 12.0 0 0 97.0]]


In [151]:
print(ytest)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


In [152]:
print(ytrain)

[1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1]


## Splitting data into Test set & Training Set


## Feature Scaling

In [153]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain[:,6:]=sc.fit_transform(xtrain[:,6:])
xtest[:,6:]=sc.fit_transform(xtest[:,6:])

In [154]:
print(xtrain)

[[1.0 0.0 0.0 86.0 1 1 -0.9941858494300261]
 [0.0 1.0 0.0 35.0 0 1 0.9574354145081887]
 [1.0 0.0 0.0 75.0 0 1 -0.9012515035282064]
 [1.0 0.0 0.0 42.0 0 0 0.9574354145081887]
 [1.0 0.0 0.0 74.0 1 1 -0.6224484658227472]
 [1.0 0.0 0.0 62.0 1 1 -1.2729888871354853]
 [0.0 1.0 0.0 24.0 0 0 0.9574354145081887]
 [0.0 1.0 0.0 48.0 0 1 1.0503697604100084]
 [1.0 0.0 0.0 58.0 0 0 -1.087120195331846]
 [0.0 1.0 0.0 45.130434782608695 1 0 0.7715667227045492]
 [0.0 1.0 0.0 15.0 0 0 0.9574354145081887]
 [0.0 0.0 1.0 70.0 0 1 0.5856980309009097]
 [1.0 0.0 0.0 52.0 1 1 -0.15777673631364833]
 [1.0 0.0 0.0 60.0 1 1 -1.2729888871354853]
 [1.0 0.0 0.0 54.0 1 1 -1.087120195331846]
 [0.0 0.0 1.0 29.0 0 0 1.0503697604100084]
 [1.0 0.0 0.0 78.0 1 1 -0.9941858494300261]
 [1.0 0.0 0.0 36.0 1 0 0.7715667227045492]
 [0.0 1.0 0.0 30.0 1 0 0.3998293390972702]
 [1.0 0.0 0.0 50.0 1 1 -0.4365797740191076]
 [0.0 0.0 1.0 18.0 0 0 1.0503697604100084]
 [1.0 0.0 0.0 69.0 0 1 -2.6670040756627817]
 [0.0 0.0 1.0 10.0 0 0 1.42210

In [155]:
print(xtest )

[[0.0 0.0 1.0 25.0 0 1 0.17205102992570073]
 [0.0 0.0 1.0 10.0 0 0 0.9513409890009328]
 [1.0 0.0 0.0 68.0 1 0 -1.1739952630224273]
 [0.0 1.0 0.0 13.0 0 0 0.7388073637985968]
 [1.0 0.0 0.0 59.0 1 0 -1.1031507212883154]
 [0.0 0.0 1.0 28.0 0 0 1.0930300724691568]
 [0.0 0.0 1.0 20.0 0 0 0.6679628220644848]
 [1.0 0.0 0.0 46.0 1 0 0.5262737385962607]
 [1.0 0.0 0.0 53.0 1 0 -2.0241297638317715]
 [0.0 0.0 1.0 16.0 0 0 0.5971182803303727]
 [1.0 0.0 0.0 38.0 0 0 -0.6072389291495313]
 [0.0 0.0 1.0 19.0 0 0 0.5971182803303727]
 [1.0 0.0 0.0 94.0 1 1 -1.3865288882247633]
 [0.0 1.0 0.0 12.0 0 0 0.9513409890009328]]


In [156]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

LogisticRegression(random_state=0)

In [158]:
Y_pred = classifier.predict(xtest)

In [160]:
print(Y_pred)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


In [165]:
print(ytest)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


In [161]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, Y_pred)

In [162]:
print(cm)

[[9 0]
 [0 5]]


In [164]:
print((9+5)/(9+5) *100)

100.0
